recipe: default.v1

# The assistant project unique identifier
assistant_id: 20250515-042817-booming-inventory

# Configuration for Rasa NLU
language: vi,en  # Supporting both Vietnamese and English

pipeline:
  # Use Underthesea for Vietnamese tokenization
  - name: components.multilingual.vietnamese.UnderthesaTokenizer
    model: vi
    intent_tokenization_flag: True
    intent_split_symbol: "_"
  
  # Extract regex features for entities
  # Define regex patterns for cryptocurrency wallet addresses
  - name: RegexFeaturizer
    case_sensitive: False
  
  # Extract grammatical and syntactical features
  - name: LexicalSyntacticFeaturizer
    
  # Use LaBSE model for multilingual support
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "rasa/LaBSE"
    cache_dir: "./cache"     # Cache transformer models
    batch_size: 16           # Optimized for 24GB RAM
    epochs: 15               # Increased from 5 to 15 for better fine-tuning
    random_seed: 42
  
  # Extract bag-of-words features with word-level n-grams
  - name: CountVectorsFeaturizer
    analyzer: "word"
    min_ngram: 1
    max_ngram: 2
  
  # Character-level features for robustness against typos
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
    
  # Intent and entity classification using DIET
  - name: DIETClassifier
    epochs: 150              # Increased from 100 to 150 
    constrain_similarities: true
    batch_strategy: "sequence"  # Changed from "balanced" to "sequence" for better learning
    evaluate_on_number_of_examples: 20  # Enable validation split for performance monitoring
    evaluate_every_number_of_epochs: 10
    checkpoint_model: true   # Save checkpoints for the best model
    entity_recognition: true
    use_masked_language_model: false
    BILOU_flag: true
    intent_tokenization_flag: true
    intent_split_symbol: "_"
    use_full_model_secure_mode: false
    share_hidden_layers: false
    batch_size: [16, 32]     # Dynamic batch sizing for better convergence
    random_seed: 42
    ranking_length: 3        # Return top 3 instead of 5 for more focused results
    
  # Map entity synonyms
  - name: EntitySynonymMapper
  
  # Handle FAQs with ResponseSelector
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: faq
    scale_loss: true
    constrain_similarities: true
    batch_size: 16
    random_seed: 42
    
  # Fallback when confidence is low
  - name: FallbackClassifier
    threshold: 0.7           # Conservative threshold for fallback
    ambiguity_threshold: 0.1
    fallback_intent_name: nlu_fallback

# Configuration for Rasa Core
policies:
  - name: MemoizationPolicy
    max_history: 5
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 5
        state_featurizer:
          - name: SingleStateFeaturizer
    
  - name: TEDPolicy
    max_history: 5
    epochs: 100              # Increased from 50 to 100 for better dialogue learning
    batch_size: 32
    random_seed: 42
    constrain_similarities: true
    
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_fallback_claude"
    enable_fallback_prediction: true
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 5
        state_featurizer:
          - name: SingleStateFeaturizer
